### ISSUE TITLE
redirect url

### ISSUE THREAD

**Issue by skapytek** [panthera-p/deezer-analytics#1]
Hello,
i put the following url in the "redirect url field": https://deezer.com but every time when i open deezer.com ill get this error: "you must enter a valid redirect url".
Can you tell me what u placed in this field?

best regards

**Comment by panthera-p** [comment]
I put "http://www.deezer.com/profile/0123456" where 0123456 is my Deezer profile number. When you open in Deezer web player your profile page from the left menu, check your browser URL after that.

**Comment by skapytek** [comment]
thanks
