### ISSUE TITLE
doesn't work in firefox 48.0.2

### ISSUE THREAD

**Issue by wow23** [panthera-p/deezer-analytics#2]
it works partially, i mean, script loads, does its job for a 20-30 seconds, and then reloads page of deezer, and this continues in loop.

**Comment by panthera-p** [comment]
Try it now. I updated few things to the latest Deezer version.

**Comment by wow23** [comment]
yeah, now it works for me (yandex browser, tampermonkey). i like your script mostly for clean "hear this" page, but all the statisctics stuff also cool.

thank you!
